import { dbConnect } from "@/lib/db";
import { withAdmin, ok, fail, parseJson } from "@/lib/http";
import { Expense } from "@/models/Expense";
import { toPlain } from "@/lib/serialize";
import { ensureRecurringExpensesUpToCurrent } from "@/lib/recurringExpenses";

export const GET = withAdmin(async () => {
  await dbConnect();
  await ensureRecurringExpensesUpToCurrent();
  const expenses = await Expense.find({}).sort({ date: -1, createdAt: -1 }).populate("projectId", "name").lean();
  return ok(toPlain(expenses));
});

export const POST = withAdmin(async (req) => {
  await dbConnect();
  const body = await parseJson(req);
  if (!body.date || !body.amount || !body.category) return fail("Missing required fields");

  const expense = await Expense.create({
    date: new Date(body.date),
    amount: Number(body.amount),
    category: String(body.category),
    vendor: String(body.vendor || ""),
    note: String(body.note || ""),
    projectId: body.projectId || null,
    isAutoGenerated: false,
  });
  const populated = await Expense.findById(expense._id).populate("projectId", "name").lean();
  return ok(toPlain(populated), 201);
});
