"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import AuthGuard from "@/components/AuthGuard";
import AppShell from "@/components/AppShell";
import Modal from "@/components/Modal";
import { apiFetch } from "@/lib/api";
import { Button, Card, Input, Select, Textarea } from "@/components/ui";
import { errorMessage } from "@/lib/errorMessage";

type ProjectOption = { _id: string; name: string };
type Expense = {
  _id: string;
  date: string;
  amount: number;
  category: string;
  vendor?: string;
  note?: string;
  projectId?: ProjectOption | string | null;
  isAutoGenerated?: boolean;
  recurringTemplateId?: string | null;
};

type RecurringExpense = {
  _id: string;
  name: string;
  amount: number;
  category: string;
  vendor?: string;
  note?: string;
  projectId?: ProjectOption | string | null;
  startDate: string;
  endDate?: string | null;
  dayOfMonth: number;
  active: boolean;
};

type ExpenseForm = {
  date: string;
  amount: string;
  category: string;
  vendor: string;
  note: string;
  projectId: string;
};

const initialForm: ExpenseForm = {
  date: new Date().toISOString().slice(0, 10),
  amount: "",
  category: "",
  vendor: "",
  note: "",
  projectId: "",
};

type RecurringForm = {
  name: string;
  amount: string;
  category: string;
  vendor: string;
  note: string;
  projectId: string;
  startDate: string;
  endDate: string;
  dayOfMonth: string;
  active: boolean;
};

const initialRecurringForm: RecurringForm = {
  name: "",
  amount: "",
  category: "",
  vendor: "",
  note: "",
  projectId: "",
  startDate: new Date().toISOString().slice(0, 10),
  endDate: "",
  dayOfMonth: "1",
  active: true,
};

const money = (n: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "ILS", maximumFractionDigits: 0 }).format(n || 0);

function formatLocalDate(value: string | Date | null | undefined) {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function sourceBadgeClass(isAuto?: boolean) {
  return isAuto
    ? "border-sky-200 bg-sky-100 text-sky-700"
    : "border-slate-200 bg-slate-100 text-slate-700";
}

export default function ExpensesPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [projects, setProjects] = useState<ProjectOption[]>([]);
  const [recurringExpenses, setRecurringExpenses] = useState<RecurringExpense[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Expense | null>(null);
  const [form, setForm] = useState<ExpenseForm>(initialForm);
  const [saving, setSaving] = useState(false);
  const [recurringOpen, setRecurringOpen] = useState(false);
  const [editingRecurring, setEditingRecurring] = useState<RecurringExpense | null>(null);
  const [recurringForm, setRecurringForm] = useState<RecurringForm>(initialRecurringForm);
  const [recurringSaving, setRecurringSaving] = useState(false);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [projectFilter, setProjectFilter] = useState("");
  const [sourceFilter, setSourceFilter] = useState<"all" | "manual" | "auto">("all");

  const categoryOptions = useMemo(
    () => Array.from(new Set(expenses.map((e) => (e.category || "").trim()).filter(Boolean))).sort(),
    [expenses]
  );

  const filteredExpenses = useMemo(() => {
    const q = search.trim().toLowerCase();
    return expenses.filter((e) => {
      const matchesSearch =
        !q ||
        [e.category, e.vendor, e.note, e.projectId && typeof e.projectId !== "string" ? e.projectId.name : ""]
          .some((v) => String(v || "").toLowerCase().includes(q));
      const matchesCategory = !categoryFilter || e.category === categoryFilter;
      const expenseProjectId = e.projectId && typeof e.projectId !== "string" ? e.projectId._id : "";
      const matchesProject = !projectFilter || expenseProjectId === projectFilter;
      const matchesSource =
        sourceFilter === "all" ||
        (sourceFilter === "auto" ? Boolean(e.isAutoGenerated) : !e.isAutoGenerated);
      return matchesSearch && matchesCategory && matchesProject && matchesSource;
    });
  }, [expenses, search, categoryFilter, projectFilter, sourceFilter]);
  const filteredExpenseTotal = filteredExpenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);
  const autoExpenseCount = filteredExpenses.filter((e) => e.isAutoGenerated).length;
  const manualExpenseCount = filteredExpenses.filter((e) => !e.isAutoGenerated).length;
  const activeRecurringCount = recurringExpenses.filter((r) => r.active).length;

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const [expRes, projRes, recurringRes] = await Promise.all([
        apiFetch<{ success: boolean; data: Expense[] }>("/api/expenses"),
        apiFetch<{ success: boolean; data: Array<{ _id: string; name: string }> }>("/api/projects"),
        apiFetch<{ success: boolean; data: RecurringExpense[] }>("/api/recurring-expenses"),
      ]);
      setExpenses(expRes.data);
      setProjects(projRes.data.map((p) => ({ _id: p._id, name: p.name })));
      setRecurringExpenses(recurringRes.data);
    } catch (e: unknown) {
      setError(errorMessage(e, "Failed to load expenses"));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  function openCreate() {
    setEditing(null);
    setForm(initialForm);
    setOpen(true);
  }

  function openRecurringCreate() {
    setEditingRecurring(null);
    setRecurringForm(initialRecurringForm);
    setRecurringOpen(true);
  }

  function openEdit(expense: Expense) {
    setEditing(expense);
    setForm({
      date: formatLocalDate(expense.date),
      amount: String(expense.amount),
      category: expense.category || "",
      vendor: expense.vendor || "",
      note: expense.note || "",
      projectId: expense.projectId && typeof expense.projectId !== "string" ? expense.projectId._id : "",
    });
    setOpen(true);
  }

  function openRecurringEdit(row: RecurringExpense) {
    setEditingRecurring(row);
    setRecurringForm({
      name: row.name || "",
      amount: String(row.amount ?? ""),
      category: row.category || "",
      vendor: row.vendor || "",
      note: row.note || "",
      projectId: row.projectId && typeof row.projectId !== "string" ? row.projectId._id : "",
      startDate: formatLocalDate(row.startDate),
      endDate: row.endDate ? formatLocalDate(row.endDate) : "",
      dayOfMonth: String(row.dayOfMonth || 1),
      active: Boolean(row.active),
    });
    setRecurringOpen(true);
  }

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setSaving(true);
    const payload = { ...form, amount: Number(form.amount), projectId: form.projectId || null };
    try {
      if (editing) {
        await apiFetch(`/api/expenses/${editing._id}`, { method: "PUT", body: JSON.stringify(payload) });
      } else {
        await apiFetch("/api/expenses", { method: "POST", body: JSON.stringify(payload) });
      }
      setOpen(false);
      await load();
    } catch (e: unknown) {
      alert(errorMessage(e, "Save failed"));
    } finally {
      setSaving(false);
    }
  }

  async function onDelete(expense: Expense) {
    if (!confirm("Delete this expense?")) return;
    try {
      await apiFetch(`/api/expenses/${expense._id}`, { method: "DELETE" });
      await load();
    } catch (e: unknown) {
      alert(errorMessage(e, "Delete failed"));
    }
  }

  async function onRecurringSubmit(e: FormEvent) {
    e.preventDefault();
    setRecurringSaving(true);
    const payload = {
      ...recurringForm,
      amount: Number(recurringForm.amount),
      dayOfMonth: Number(recurringForm.dayOfMonth || 1),
      endDate: recurringForm.endDate || null,
      projectId: recurringForm.projectId || null,
    };
    try {
      if (editingRecurring) {
        await apiFetch(`/api/recurring-expenses/${editingRecurring._id}`, {
          method: "PUT",
          body: JSON.stringify(payload),
        });
      } else {
        await apiFetch("/api/recurring-expenses", { method: "POST", body: JSON.stringify(payload) });
      }
      setRecurringOpen(false);
      await load();
    } catch (e: unknown) {
      alert(errorMessage(e, "Save recurring expense failed"));
    } finally {
      setRecurringSaving(false);
    }
  }

  async function onRecurringDelete(row: RecurringExpense) {
    if (!confirm(`Delete recurring expense "${row.name}"?`)) return;
    try {
      await apiFetch(`/api/recurring-expenses/${row._id}`, { method: "DELETE" });
      await load();
    } catch (e: unknown) {
      alert(errorMessage(e, "Delete recurring expense failed"));
    }
  }

  return (
    <AuthGuard>
      <AppShell
        title="Expenses"
        actions={
          <div className="flex flex-wrap gap-2">
            <Input
              placeholder="Search category / vendor / note / project"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-80"
            />
            <Select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} className="w-44">
              <option value="">All categories</option>
              {categoryOptions.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </Select>
            <Select value={projectFilter} onChange={(e) => setProjectFilter(e.target.value)} className="w-44">
              <option value="">All projects</option>
              {projects.map((p) => (
                <option key={p._id} value={p._id}>
                  {p.name}
                </option>
              ))}
            </Select>
            <Select
              value={sourceFilter}
              onChange={(e) => setSourceFilter(e.target.value as "all" | "manual" | "auto")}
              className="w-36"
            >
              <option value="all">All sources</option>
              <option value="manual">Manual</option>
              <option value="auto">Auto monthly</option>
            </Select>
            <Button type="button" variant="secondary" onClick={openRecurringCreate}>
              Add Auto Monthly
            </Button>
            <Button onClick={openCreate}>Add Expense</Button>
          </div>
        }
      >
        <Card className="bg-gradient-to-b from-white to-slate-50/60">
          {loading ? (
            <div className="grid min-h-52 place-items-center text-sm text-slate-500">Loading expenses...</div>
          ) : error ? (
            <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>
          ) : (
            <div className="space-y-3">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <h2 className="text-lg font-semibold tracking-tight text-slate-900">Expenses Ledger</h2>
                  <p className="text-sm text-slate-500">Manual and auto-generated monthly expenses in one timeline.</p>
                </div>
                <div className="flex flex-wrap gap-2 text-xs">
                  <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 font-medium text-slate-600">
                    {filteredExpenses.length} shown
                  </span>
                  <span className="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-1 font-medium text-sky-700">
                    {autoExpenseCount} auto
                  </span>
                  <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 font-medium text-slate-700">
                    {manualExpenseCount} manual
                  </span>
                  <span className="rounded-full border border-rose-200 bg-rose-50 px-2.5 py-1 font-medium text-rose-700">
                    {money(filteredExpenseTotal)}
                  </span>
                </div>
              </div>

              <div className="overflow-x-auto rounded-2xl border border-slate-200/90 bg-white/85 shadow-sm">
                <table className="min-w-full text-sm">
                  <thead className="sticky top-0 bg-white/95 text-left text-slate-500 backdrop-blur">
                  <tr>
                    <th className="px-4 py-3 pr-4">Date</th>
                    <th className="py-3 pr-4">Amount</th>
                    <th className="py-3 pr-4">Category</th>
                    <th className="py-3 pr-4">Source</th>
                    <th className="py-3 pr-4">Vendor</th>
                    <th className="py-3 pr-4">Project</th>
                    <th className="py-3 pr-4">Note</th>
                    <th className="py-3 pr-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredExpenses.map((e) => (
                    <tr key={e._id} className="border-t border-slate-100/90 transition hover:bg-slate-50/70">
                      <td className="px-4 py-3 pr-4 font-medium text-slate-800">{formatLocalDate(e.date)}</td>
                      <td className="py-3 pr-4 font-medium text-slate-900">{money(e.amount)}</td>
                      <td className="py-3 pr-4">
                        <span className="inline-flex rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-700">
                          {e.category}
                        </span>
                      </td>
                      <td className="py-3 pr-4">
                        <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${sourceBadgeClass(e.isAutoGenerated)}`}>
                          {e.isAutoGenerated ? "Auto" : "Manual"}
                        </span>
                      </td>
                      <td className="py-3 pr-4 text-slate-700">{e.vendor || "-"}</td>
                      <td className="py-3 pr-4 text-slate-700">
                        {e.projectId && typeof e.projectId !== "string" ? e.projectId.name : "-"}
                      </td>
                      <td className="py-3 pr-4">
                        <div className="max-w-xs truncate text-slate-600">{e.note || "-"}</div>
                      </td>
                      <td className="py-3 pr-4">
                        <div className="flex justify-end gap-2">
                          <button
                            className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm transition hover:bg-slate-50"
                            onClick={() => openEdit(e)}
                          >
                            Edit
                          </button>
                          <button
                            className="inline-flex items-center rounded-xl border border-rose-200 bg-rose-50 px-3 py-1.5 text-xs font-medium text-rose-700 shadow-sm transition hover:bg-rose-100"
                            onClick={() => onDelete(e)}
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                  {!filteredExpenses.length && (
                    <tr>
                      <td colSpan={8} className="py-10 text-center text-slate-500">
                        {expenses.length ? "No expenses match your filters." : "No expenses yet."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            </div>
          )}
        </Card>

        <Card className="bg-gradient-to-b from-white to-slate-50/60">
          <div className="mb-3 flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold tracking-tight text-slate-900">Auto Monthly Expense Templates</h2>
              <p className="text-sm text-slate-500">
                Templates that auto-generate one expense per month up to current month.
              </p>
            </div>
            <div className="flex gap-2 text-xs">
              <span className="rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 font-medium text-emerald-700">
                {activeRecurringCount} active
              </span>
              <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 font-medium text-slate-600">
                {recurringExpenses.length} total
              </span>
            </div>
          </div>
          <div className="overflow-x-auto rounded-2xl border border-slate-200/90 bg-white/85 shadow-sm">
            <table className="min-w-full text-sm">
              <thead className="sticky top-0 bg-white/95 text-left text-slate-500 backdrop-blur">
                <tr>
                  <th className="px-4 py-3 pr-4">Name</th>
                  <th className="py-3 pr-4">Amount</th>
                  <th className="py-3 pr-4">Category</th>
                  <th className="py-3 pr-4">Project</th>
                  <th className="py-3 pr-4">Starts</th>
                  <th className="py-3 pr-4">Ends</th>
                  <th className="py-3 pr-4">Day</th>
                  <th className="py-3 pr-4">Status</th>
                  <th className="py-3 pr-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {recurringExpenses.map((r) => (
                  <tr key={r._id} className="border-t border-slate-100/90 transition hover:bg-slate-50/70">
                    <td className="px-4 py-3 pr-4">
                      <div className="font-medium text-slate-900">{r.name}</div>
                      <div className="max-w-xs truncate text-xs text-slate-500">{r.note || "No notes"}</div>
                    </td>
                    <td className="py-3 pr-4 font-medium text-slate-900">{money(r.amount)}</td>
                    <td className="py-3 pr-4">
                      <span className="inline-flex rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-700">
                        {r.category}
                      </span>
                    </td>
                    <td className="py-3 pr-4 text-slate-700">
                      {r.projectId && typeof r.projectId !== "string" ? r.projectId.name : "-"}
                    </td>
                    <td className="py-3 pr-4 text-slate-700">{formatLocalDate(r.startDate)}</td>
                    <td className="py-3 pr-4 text-slate-700">{r.endDate ? formatLocalDate(r.endDate) : "-"}</td>
                    <td className="py-3 pr-4">
                      <span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-700">
                        Day {r.dayOfMonth}
                      </span>
                    </td>
                    <td className="py-3 pr-4">
                      <span
                        className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${
                          r.active
                            ? "border-emerald-200 bg-emerald-100 text-emerald-700"
                            : "border-slate-200 bg-slate-100 text-slate-700"
                        }`}
                      >
                        {r.active ? "Active" : "Paused"}
                      </span>
                    </td>
                    <td className="py-3 pr-4">
                      <div className="flex justify-end gap-2">
                        <button
                          className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm transition hover:bg-slate-50"
                          onClick={() => openRecurringEdit(r)}
                        >
                          Edit
                        </button>
                        <button
                          className="inline-flex items-center rounded-xl border border-rose-200 bg-rose-50 px-3 py-1.5 text-xs font-medium text-rose-700 shadow-sm transition hover:bg-rose-100"
                          onClick={() => onRecurringDelete(r)}
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
                {!recurringExpenses.length && (
                  <tr>
                    <td colSpan={9} className="py-10 text-center text-slate-500">
                      No auto monthly expense templates yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </Card>

        <Modal open={open} title={editing ? "Edit Expense" : "Add Expense"} onClose={() => setOpen(false)}>
          <form onSubmit={onSubmit} className="space-y-3">
            <div className="grid gap-3 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium">Date</label>
                <Input type="date" required value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Amount</label>
                <Input
                  type="number"
                  min="0"
                  step="0.01"
                  required
                  value={form.amount}
                  onChange={(e) => setForm({ ...form, amount: e.target.value })}
                />
              </div>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium">Category</label>
                <Input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Vendor</label>
                <Input value={form.vendor} onChange={(e) => setForm({ ...form, vendor: e.target.value })} />
              </div>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium">Project (optional)</label>
              <Select value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })}>
                <option value="">No project</option>
                {projects.map((p) => (
                  <option key={p._id} value={p._id}>
                    {p.name}
                  </option>
                ))}
              </Select>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium">Note</label>
              <Textarea rows={4} value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} />
            </div>
            <div className="flex justify-end gap-2">
              <Button type="button" variant="secondary" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button disabled={saving}>{saving ? "Saving..." : "Save"}</Button>
            </div>
          </form>
        </Modal>

        <Modal
          open={recurringOpen}
          title={editingRecurring ? "Edit Auto Monthly Expense" : "Add Auto Monthly Expense"}
          onClose={() => setRecurringOpen(false)}
        >
          <form onSubmit={onRecurringSubmit} className="space-y-3">
            <div className="grid gap-3 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium">Name</label>
                <Input
                  required
                  value={recurringForm.name}
                  onChange={(e) => setRecurringForm({ ...recurringForm, name: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Amount</label>
                <Input
                  type="number"
                  min="0"
                  step="0.01"
                  required
                  value={recurringForm.amount}
                  onChange={(e) => setRecurringForm({ ...recurringForm, amount: e.target.value })}
                />
              </div>
            </div>

            <div className="grid gap-3 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium">Category</label>
                <Input
                  required
                  value={recurringForm.category}
                  onChange={(e) => setRecurringForm({ ...recurringForm, category: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Vendor</label>
                <Input value={recurringForm.vendor} onChange={(e) => setRecurringForm({ ...recurringForm, vendor: e.target.value })} />
              </div>
            </div>

            <div className="grid gap-3 md:grid-cols-3">
              <div>
                <label className="mb-1 block text-sm font-medium">Start Date</label>
                <Input
                  type="date"
                  required
                  value={recurringForm.startDate}
                  onChange={(e) => setRecurringForm({ ...recurringForm, startDate: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">End Date (optional)</label>
                <Input
                  type="date"
                  value={recurringForm.endDate}
                  onChange={(e) => setRecurringForm({ ...recurringForm, endDate: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Day of Month</label>
                <Input
                  type="number"
                  min="1"
                  max="28"
                  required
                  value={recurringForm.dayOfMonth}
                  onChange={(e) => setRecurringForm({ ...recurringForm, dayOfMonth: e.target.value })}
                />
              </div>
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium">Project (optional)</label>
              <Select
                value={recurringForm.projectId}
                onChange={(e) => setRecurringForm({ ...recurringForm, projectId: e.target.value })}
              >
                <option value="">No project</option>
                {projects.map((p) => (
                  <option key={p._id} value={p._id}>
                    {p.name}
                  </option>
                ))}
              </Select>
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium">Note</label>
              <Textarea
                rows={3}
                value={recurringForm.note}
                onChange={(e) => setRecurringForm({ ...recurringForm, note: e.target.value })}
              />
            </div>

            <label className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                checked={recurringForm.active}
                onChange={(e) => setRecurringForm({ ...recurringForm, active: e.target.checked })}
              />
              Active (generate monthly expenses)
            </label>

            <div className="flex justify-end gap-2">
              <Button type="button" variant="secondary" onClick={() => setRecurringOpen(false)}>
                Cancel
              </Button>
              <Button disabled={recurringSaving}>{recurringSaving ? "Saving..." : "Save"}</Button>
            </div>
          </form>
        </Modal>
      </AppShell>
    </AuthGuard>
  );
}
