import mongoose, { Schema, Types } from "mongoose";

export type ExpenseDoc = {
  _id: Types.ObjectId;
  date: Date;
  amount: number;
  category: string;
  vendor?: string;
  note?: string;
  projectId: Types.ObjectId | null;
  isAutoGenerated?: boolean;
  recurringTemplateId?: Types.ObjectId | null;
  recurringYear?: number | null;
  recurringMonth?: number | null;
  createdAt: Date;
  updatedAt: Date;
};

const ExpenseSchema = new Schema<ExpenseDoc>(
  {
    date: { type: Date, required: true, index: true },
    amount: { type: Number, required: true, min: 0 },
    category: { type: String, required: true, trim: true, index: true },
    vendor: { type: String, default: "" },
    note: { type: String, default: "" },
    projectId: { type: Schema.Types.ObjectId, ref: "Project", default: null, index: true },
    isAutoGenerated: { type: Boolean, default: false, index: true },
    recurringTemplateId: { type: Schema.Types.ObjectId, ref: "RecurringExpense", default: null, index: true },
    recurringYear: { type: Number, default: null },
    recurringMonth: { type: Number, default: null, min: 1, max: 12 },
  },
  { timestamps: true }
);

ExpenseSchema.index(
  { recurringTemplateId: 1, recurringYear: 1, recurringMonth: 1 },
  {
    unique: true,
    partialFilterExpression: { recurringTemplateId: { $type: "objectId" } },
  }
);

export const Expense = mongoose.models.Expense || mongoose.model<ExpenseDoc>("Expense", ExpenseSchema);

